#!/usr/bin/env bash
set -euo pipefail

STUDIO_BRAIN_HEALTH_HOST="${STUDIO_BRAIN_HEALTH_HOST:-${STUDIO_BRAIN_HOST:-192.168.1.226}}"
STUDIO_BRAIN_HEALTH_PORT="${STUDIO_BRAIN_HEALTH_PORT:-8787}"
HEALTHCHECK_TIMEOUT_SECONDS="${STUDIO_BRAIN_HEALTHCHECK_TIMEOUT_SECONDS:-5}"

curl -fsS --max-time "${HEALTHCHECK_TIMEOUT_SECONDS}" "http://${STUDIO_BRAIN_HEALTH_HOST}:${STUDIO_BRAIN_HEALTH_PORT}/healthz" >/dev/null
curl -fsS --max-time "${HEALTHCHECK_TIMEOUT_SECONDS}" "http://${STUDIO_BRAIN_HEALTH_HOST}:${STUDIO_BRAIN_HEALTH_PORT}/readyz" >/dev/null
