const FRESHNESS_TIERS = {
  loop: { maxAgeHours: 6, description: "active slice-loop evidence that should be refreshed during the current work session" },
  daily: { maxAgeHours: 24, description: "daily operational evidence that can age through a normal work day" },
  weekly: { maxAgeHours: 168, description: "slower-moving evidence that is still useful across a weekly ops review" },
};

const PRODUCER_METADATA = {
  "tooling-quality-report": {
    producerCommand: "node scripts/ops/tooling_quality_report.mjs --mode all --json --write",
    producerStep: "tooling-quality",
    safeWriteRoot: "output/ops/tooling-quality",
    consumers: ["tooling-findings-export", "installed-tool-inventory", "tool-install-recommendations", "admin-effectivity-audit"],
    requiredFor: ["ops-ci-validate", "five-slice-audit"],
  },
  "tooling-findings-export": {
    producerCommand: "node scripts/ops/tooling_findings_export.mjs --json --write",
    producerStep: "tooling-findings",
    safeWriteRoot: "output/ops/tooling-quality",
    consumers: ["ops-work-packet", "admin-effectivity-audit"],
    requiredFor: ["work-packet-generation"],
  },
  "installed-tool-inventory": {
    producerCommand: "node scripts/ops/installed_tool_inventory.mjs --json --write",
    producerStep: "tool-inventory",
    safeWriteRoot: "output/ops/effectivity",
    consumers: ["tool-install-recommendations", "admin-effectivity-audit"],
    requiredFor: ["tooling-quality-audit"],
  },
  "tool-install-recommendations": {
    producerCommand: "node scripts/ops/tool_install_recommendations.mjs --json --write",
    producerStep: "tool-install-recommendations",
    safeWriteRoot: "output/ops/effectivity",
    consumers: ["ops-work-packet", "pr-readiness-packet"],
    requiredFor: ["safe-tooling-recommendations"],
  },
  "admin-effectivity-audit": {
    producerCommand: "node scripts/ops/admin_effectivity_audit.mjs --json --write --last 5 --slice-run-id admin-infra-20260507",
    producerStep: "admin-effectivity-audit",
    safeWriteRoot: "output/ops/effectivity",
    consumers: ["admin-effectivity-trend", "ops-work-packet", "mission-control-admin-import"],
    requiredFor: ["five-slice-audit"],
  },
  "admin-effectivity-trend": {
    producerCommand: "node scripts/ops/admin_effectivity_trend.mjs --json --write --limit 10",
    producerStep: "admin-effectivity-trend",
    safeWriteRoot: "output/ops/effectivity",
    consumers: ["operator-handoff", "five-slice-audit"],
    requiredFor: ["trend-review"],
  },
  "slice-ledger-summary": {
    producerCommand: "node scripts/ops/slice_ledger.mjs --summary --last 5 --run-id admin-infra-20260507 --json",
    producerStep: "slice-ledger",
    safeWriteRoot: "output/ops/effectivity",
    consumers: ["admin-effectivity-audit", "pr-readiness-packet"],
    requiredFor: ["slice-accountability"],
  },
  "host-drift-manifest": {
    producerCommand: "node scripts/ops/host_drift_manifest.mjs --json --write",
    producerStep: "host-drift-manifest",
    safeWriteRoot: "output/ops/host-drift",
    consumers: ["ops-work-packet", "operator-handoff"],
    requiredFor: ["host-drift-review"],
  },
  "ops-work-packet": {
    producerCommand: "node scripts/studiobrain-ops-work-packet.mjs --json --write --max-packets 8",
    producerStep: "work-packet",
    safeWriteRoot: "output/ops/swarm",
    consumers: ["work-packet-quality-lint", "packet-outcome-report", "pr-readiness-packet"],
    requiredFor: ["next-slice-selection"],
  },
  "work-packet-quality-lint": {
    producerCommand: "node scripts/ops/work_packet_quality_lint.mjs --json --write",
    producerStep: "work-packet-quality",
    safeWriteRoot: "output/ops/swarm",
    consumers: ["stale-backlog-packet-report", "pr-readiness-packet", "operator-handoff"],
    requiredFor: ["work-packet-quality"],
  },
  "stale-backlog-packet-report": {
    producerCommand: "node scripts/ops/stale_backlog_packet_report.mjs --json --write",
    producerStep: "stale-backlog-packets",
    safeWriteRoot: "output/ops/swarm",
    consumers: ["pr-readiness-packet", "operator-handoff", "backlog-refresh"],
    requiredFor: ["backlog-retirement-steering"],
  },
  "packet-outcome-report": {
    producerCommand: "node scripts/ops/packet_outcome_report.mjs --json --write",
    producerStep: "packet-outcome-report",
    safeWriteRoot: "output/ops/swarm",
    consumers: ["admin-effectivity-audit", "pr-readiness-packet"],
    requiredFor: ["work-packet-effectivity"],
  },
  "swarm-lane-preflight": {
    producerCommand: "node scripts/ops/swarm_lane_preflight.mjs --lane tooling --base origin/main --json --write",
    producerStep: "swarm-preflight",
    safeWriteRoot: "output/ops/swarm-lane-preflight",
    consumers: ["ops-work-packet", "ops-wave-runner"],
    requiredFor: ["safe-swarm-delegation"],
  },
  "ops-wave-runner": {
    producerCommand: "node scripts/ops/ops_wave_runner.mjs --json --write",
    producerStep: "ops-wave-runner",
    safeWriteRoot: "output/ops/waves",
    consumers: ["pr-readiness-packet"],
    requiredFor: ["ordered-artifact-refresh"],
  },
  "pr-stack-audit": {
    producerCommand: "node scripts/ops/pr_stack_audit.mjs --json --write",
    producerStep: "pr-stack-audit",
    safeWriteRoot: "output/ops/pr-stack",
    consumers: ["operator-handoff", "merge-planning", "ops-work-packet"],
    requiredFor: ["stack-discipline", "in-flight-work-suppression"],
  },
  "pr-readiness-packet": {
    producerCommand: "node scripts/ops/pr_readiness_packet.mjs --json --write",
    producerStep: "pr-readiness",
    safeWriteRoot: "output/ops/pr-readiness",
    consumers: ["pr-body", "review-handoff"],
    requiredFor: ["reviewable-prs"],
  },
  "post-merge-verification-packet": {
    producerCommand: "node scripts/ops/post_merge_verification_packet.mjs --json --write",
    producerStep: "post-merge-verification",
    safeWriteRoot: "output/ops/post-merge",
    consumers: ["pr-readiness-packet", "operator-handoff", "post-merge-issue"],
    requiredFor: ["post-merge-verification"],
  },
  "incident-bundle-v2-summary": {
    producerCommand: "INCIDENT_BUNDLE_V2_SMOKE=1 INCIDENT_INCLUDE_POST_DEPLOY=0 INCIDENT_INCLUDE_LOGS=0 bash scripts/ops/incident_bundle_v2.sh output/ops/incidents-v2/registry-smoke",
    producerStep: "incident-bundle-v2",
    safeWriteRoot: "output/ops/incidents-v2",
    consumers: ["pr-readiness-packet", "incident-response"],
    requiredFor: ["pre-incident-mutation-evidence"],
  },
  "artifact-schema-validation": {
    producerCommand: "node scripts/ops/validate_ops_artifacts.mjs --json --write",
    producerStep: "artifact-validation",
    safeWriteRoot: "output/ops/artifact-validation",
    consumers: ["ops-wave-runner", "pr-readiness-packet"],
    requiredFor: ["artifact-contract-health"],
  },
};

const OPS_ARTIFACT_REGISTRY = [
  {
    id: "tooling-quality-report",
    artifact: "output/ops/tooling-quality/tooling-quality-latest.json",
    schema: "schemas/ops/tooling-quality-report.v1.schema.json",
    freshnessTier: "daily",
  },
  {
    id: "tooling-findings-export",
    artifact: "output/ops/tooling-quality/tooling-findings-latest.json",
    schema: "schemas/ops/tooling-findings-export.v1.schema.json",
    freshnessTier: "daily",
  },
  {
    id: "installed-tool-inventory",
    artifact: "output/ops/effectivity/installed-tool-inventory-latest.json",
    schema: "schemas/ops/installed-tool-inventory.v1.schema.json",
    freshnessTier: "daily",
  },
  {
    id: "tool-install-recommendations",
    artifact: "output/ops/effectivity/tool-install-recommendations-latest.json",
    schema: "schemas/ops/tool-install-recommendations.v1.schema.json",
    freshnessTier: "daily",
  },
  {
    id: "admin-effectivity-audit",
    artifact: "output/ops/effectivity/admin-effectivity-audit-latest.json",
    schema: "schemas/ops/admin-effectivity-audit.v1.schema.json",
    freshnessTier: "loop",
  },
  {
    id: "admin-effectivity-trend",
    artifact: "output/ops/effectivity/admin-effectivity-trend-latest.json",
    schema: "schemas/ops/admin-effectivity-trend.v1.schema.json",
    freshnessTier: "loop",
  },
  {
    id: "slice-ledger-summary",
    artifact: "output/ops/effectivity/slice-ledger-latest.json",
    schema: "schemas/ops/slice-ledger-summary.v1.schema.json",
    freshnessTier: "loop",
  },
  {
    id: "host-drift-manifest",
    artifact: "output/ops/host-drift/host-drift-manifest-latest.json",
    schema: "schemas/ops/host-drift-manifest.v1.schema.json",
    freshnessTier: "loop",
  },
  {
    id: "ops-work-packet",
    artifact: "output/ops/swarm/latest-work-packet.json",
    schema: "schemas/ops/ops-work-packet.v1.schema.json",
    freshnessTier: "loop",
  },
  {
    id: "work-packet-quality-lint",
    artifact: "output/ops/swarm/work-packet-quality-latest.json",
    schema: "schemas/ops/work-packet-quality-lint.v1.schema.json",
    freshnessTier: "loop",
  },
  {
    id: "stale-backlog-packet-report",
    artifact: "output/ops/swarm/stale-backlog-packets-latest.json",
    schema: "schemas/ops/stale-backlog-packet-report.v1.schema.json",
    freshnessTier: "loop",
  },
  {
    id: "packet-outcome-report",
    artifact: "output/ops/swarm/packet-outcome-report-latest.json",
    schema: "schemas/ops/packet-outcome-report.v1.schema.json",
    freshnessTier: "loop",
  },
  {
    id: "swarm-lane-preflight",
    artifact: "output/ops/swarm-lane-preflight/swarm-lane-preflight-latest.json",
    schema: "schemas/ops/swarm-lane-preflight.v1.schema.json",
    freshnessTier: "loop",
  },
  {
    id: "ops-wave-runner",
    artifact: "output/ops/waves/ops-wave-runner-latest.json",
    schema: "schemas/ops/ops-wave-runner.v1.schema.json",
    freshnessTier: "loop",
  },
  {
    id: "pr-stack-audit",
    artifact: "output/ops/pr-stack/pr-stack-audit-latest.json",
    schema: "schemas/ops/pr-stack-audit.v1.schema.json",
    freshnessTier: "loop",
  },
  {
    id: "pr-readiness-packet",
    artifact: "output/ops/pr-readiness/pr-readiness-latest.json",
    schema: "schemas/ops/pr-readiness-packet.v1.schema.json",
    freshnessTier: "loop",
    gitHeadField: "scope.head",
  },
  {
    id: "post-merge-verification-packet",
    artifact: "output/ops/post-merge/post-merge-verification-latest.json",
    schema: "schemas/ops/post-merge-verification-packet.v1.schema.json",
    freshnessTier: "loop",
    gitHeadField: "scope.head",
  },
  {
    id: "incident-bundle-v2-summary",
    artifact: "output/ops/incidents-v2/incident-bundle-v2-latest.json",
    schema: "schemas/ops/incident-bundle-v2-summary.v1.schema.json",
    freshnessTier: "loop",
  },
  {
    id: "artifact-schema-validation",
    artifact: "output/ops/artifact-validation/artifact-schema-validation-latest.json",
    schema: "schemas/ops/artifact-schema-validation.v1.schema.json",
    freshnessTier: "loop",
  },
];

function defaultArtifactRegistry() {
  return OPS_ARTIFACT_REGISTRY.map((entry) => ({
    ...entry,
    ...(PRODUCER_METADATA[entry.id] || {}),
    maxAgeHours: FRESHNESS_TIERS[entry.freshnessTier]?.maxAgeHours ?? FRESHNESS_TIERS.daily.maxAgeHours,
  }));
}

export { defaultArtifactRegistry, FRESHNESS_TIERS, OPS_ARTIFACT_REGISTRY, PRODUCER_METADATA };
