#!/usr/bin/env bash
set -u

# Read-only import directory pressure report.
# This script prints sizes, ages, and cleanup classifications only. It never
# reads imported file contents, deletes files, moves files, compresses files, or
# prints environment variables.

TARGET_DIR="${IMPORT_DIR:-/home/wuff/imports}"
TOP_N="${TOP_N:-40}"
PREVIOUS_REPORT=""

usage() {
  cat <<'EOF'
Usage: scripts/ops/import_pressure.sh [--target DIR] [--top N] [--previous FILE]

Read-only Studio Brain import pressure report.

Options:
  --target DIR      Import directory to inspect. Defaults to IMPORT_DIR or /home/wuff/imports.
  --top N           Number of largest immediate children to show. Defaults to TOP_N or 40.
  --previous FILE   Optional earlier report generated by this script; prints total-size delta.
  -h, --help        Show this help.

Safety:
  - Does not print file contents.
  - Does not print environment variables or secrets.
  - Does not delete, move, compress, chmod, chown, or modify anything.
  - Degrades gracefully when the target directory is unavailable.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --target)
      TARGET_DIR="${2:-}"
      shift 2
      ;;
    --top)
      TOP_N="${2:-}"
      shift 2
      ;;
    --previous)
      PREVIOUS_REPORT="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

section() {
  printf '\n## %s\n' "$1"
}

warn() {
  printf 'WARN: %s\n' "$1"
}

safe_du_bytes() {
  local path="$1"
  du -sb -- "$path" 2>/dev/null | awk '{print $1}'
}

safe_du_human() {
  local path="$1"
  du -sh -- "$path" 2>/dev/null | awk '{print $1}'
}

age_bucket() {
  local days="$1"
  if [ "$days" -lt 7 ]; then
    printf '0-6d_recent'
  elif [ "$days" -lt 30 ]; then
    printf '7-29d_watch'
  elif [ "$days" -lt 90 ]; then
    printf '30-89d_review'
  else
    printf '90d_plus_review'
  fi
}

cleanup_class() {
  local path="$1"
  local days="$2"
  local base lower
  base="$(basename -- "$path")"
  lower="$(printf '%s' "$base" | tr '[:upper:]' '[:lower:]')"

  if [ "$days" -lt 7 ]; then
    printf 'do_not_touch_recent'
  elif printf '%s' "$lower" | grep -Eq '(^|[-_.])(tmp|temp|cache|scratch)([-_.]|$)'; then
    printf 'safe_with_backup'
  else
    printf 'requires_human_approval'
  fi
}

section "Report Metadata"
printf 'generated_at: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
printf 'host: %s\n' "$(hostname 2>/dev/null || printf unknown)"
printf 'target_dir: %s\n' "$TARGET_DIR"
printf 'scope: read_only_import_pressure\n'
printf 'safety: no_delete_no_move_no_compress_no_content_no_env\n'

if ! [[ "$TOP_N" =~ ^[0-9]+$ ]] || [ "$TOP_N" -lt 1 ]; then
  warn "--top must be a positive integer; using 40"
  TOP_N=40
fi

if [ ! -e "$TARGET_DIR" ]; then
  section "Target Status"
  printf 'target_exists: no\n'
  printf 'status: unavailable\n'
  exit 0
fi

if [ ! -d "$TARGET_DIR" ]; then
  section "Target Status"
  printf 'target_exists: yes\n'
  printf 'target_is_directory: no\n'
  printf 'status: unsupported_target_type\n'
  exit 0
fi

CURRENT_BYTES="$(safe_du_bytes "$TARGET_DIR")"
CURRENT_HUMAN="$(safe_du_human "$TARGET_DIR")"

section "Target Summary"
printf 'target_exists: yes\n'
printf 'target_is_directory: yes\n'
printf 'target_total_bytes: %s\n' "${CURRENT_BYTES:-unknown}"
printf 'target_total_human: %s\n' "${CURRENT_HUMAN:-unknown}"
df -hT -- "$TARGET_DIR" 2>/dev/null || warn "df unavailable for target"

section "Delta From Previous Report"
if [ -n "$PREVIOUS_REPORT" ] && [ -r "$PREVIOUS_REPORT" ]; then
  previous_bytes="$(grep -E '^target_total_bytes: [0-9]+$' "$PREVIOUS_REPORT" | tail -n 1 | awk '{print $2}')"
  if [ -n "${previous_bytes:-}" ] && [ -n "${CURRENT_BYTES:-}" ]; then
    delta_bytes=$((CURRENT_BYTES - previous_bytes))
    printf 'previous_report: %s\n' "$PREVIOUS_REPORT"
    printf 'previous_total_bytes: %s\n' "$previous_bytes"
    printf 'current_total_bytes: %s\n' "$CURRENT_BYTES"
    printf 'delta_bytes: %s\n' "$delta_bytes"
  else
    warn "previous report did not include a parseable target_total_bytes line"
  fi
else
  printf 'previous_report: unavailable\n'
  printf 'delta_status: provide --previous FILE to compute growth delta\n'
fi

section "Largest Immediate Children"
printf 'size\tpath\n'
while IFS= read -r -d '' child; do
  size="$(safe_du_human "$child")"
  printf '%s\t%s\n' "${size:-unknown}" "$child"
done < <(find "$TARGET_DIR" -xdev -mindepth 1 -maxdepth 1 -print0 2>/dev/null) | sort -h | tail -n "$TOP_N"

section "Immediate Child Age Buckets"
find "$TARGET_DIR" -xdev -mindepth 1 -maxdepth 1 -printf '%T@\n' 2>/dev/null \
  | awk -v now="$(date +%s)" '
      {
        days=int((now - int($1)) / 86400);
        if (days < 7) bucket="0-6d_recent";
        else if (days < 30) bucket="7-29d_watch";
        else if (days < 90) bucket="30-89d_review";
        else bucket="90d_plus_review";
        counts[bucket]++;
      }
      END {
        if (length(counts) == 0) {
          print "no_children";
        } else {
          for (bucket in counts) print bucket, counts[bucket];
        }
      }' | sort

section "Cleanup Candidate Classification"
printf 'class\tage_days\tsize\tpath\n'
now_epoch="$(date +%s)"
while IFS= read -r -d '' child; do
  mtime="$(stat -c '%Y' -- "$child" 2>/dev/null || printf '')"
  if [ -z "$mtime" ]; then
    printf 'requires_human_approval\tunknown\t%s\t%s\n' "$(safe_du_human "$child")" "$child"
    continue
  fi
  age_days=$(( (now_epoch - mtime) / 86400 ))
  class="$(cleanup_class "$child" "$age_days")"
  printf '%s\t%s\t%s\t%s\n' "$class" "$age_days" "$(safe_du_human "$child")" "$child"
done < <(find "$TARGET_DIR" -xdev -mindepth 1 -maxdepth 1 -print0 2>/dev/null) \
  | sort -k1,1 -k2,2nr | sed -n "1,${TOP_N}p"

section "Approval Rules"
cat <<'EOF'
| Classification | Meaning | Allowed action from this report |
| --- | --- | --- |
| do_not_touch_recent | Recently modified target data. | Observe only. |
| safe_with_backup | Cache/tmp-looking name and older than 7 days. | Human review plus backup first. |
| requires_human_approval | Import evidence or source-of-truth status is unknown. | Approval required before archive/delete/move/compress. |
| do_not_touch | Sensitive, active, or unclear operational data. | Do not touch automatically. |
EOF
