import type {
  ConsumableStock,
  MaintenanceTask,
  PrintJobRequest,
  PrintLibraryItem,
  PrinterAsset,
} from "./model";

export type FabricationDryRunFixture = {
  label: string;
  request: PrintJobRequest;
  expectedRoute: "library_reuse" | "custom_job" | "escalate";
  expectedOutcome: "planned" | "stock_alert" | "escalated";
};

export const bambuX1CPrinterAsset: PrinterAsset = {
  id: "printer.bambu_x1c_studio",
  name: "Studio Bambu X1C",
  model: "Bambu X1C",
  safeMaterials: ["PLA", "PETG"],
  nozzleSetup: "0.4mm hardened steel nozzle",
  buildPlate: "textured PEI plate",
  operatingConstraints: [
    "Human approves every physical print start and print removal.",
    "PLA and PETG only for v1 fabrication cell operations.",
    "Use only studio-safe tooling, infrastructure, and maintenance jobs in v1.",
    "Do not accept member-facing SLA work or unattended risky jobs in this lane.",
  ],
  maintenanceIntervals: [
    {
      taskType: "build_plate_cleaning",
      intervalHours: 12,
      rationale: "Keep first-layer reliability stable for repeatable tooling runs.",
    },
    {
      taskType: "full_calibration",
      intervalHours: 40,
      rationale: "Reset drift before it turns into queue noise.",
    },
    {
      taskType: "nozzle_inspection",
      intervalHours: 60,
      rationale: "Catch wear before it damages repeatability or surface finish.",
    },
  ],
  status: "idle",
  notes: [
    "Treat the printer as a Studio Brain-managed fabrication cell, not a member booking surface.",
    "Pilot target: prove saved time or saved purchases within 30 days.",
  ],
};

export const fabricationSeedLibrary: PrintLibraryItem[] = [
  {
    id: "library.glaze_test_tile_rack",
    name: "Glaze test tile rack",
    lane: "ceramics_tooling",
    intendedUse: "Hold glaze test tiles in repeatable firing or drying batches.",
    aliases: ["glaze tile rack", "test tile rack", "glaze-test rack"],
    approvedMaterial: "PLA",
    approvedSettings: {
      layerHeightMm: 0.2,
      nozzleMm: 0.4,
      infillPct: 20,
      supportStrategy: "none",
      buildPlate: "textured PEI",
    },
    estimatedGrams: 84,
    estimatedRuntimeMinutes: 255,
    evidenceChecklist: ["photo on shelf", "batch label legibility", "tile fit check"],
    replacementTrigger: "Reprint when an existing rack warps or a new glaze series starts.",
  },
  {
    id: "library.slab_guide_5mm",
    name: "Slab guide set 5mm",
    lane: "ceramics_tooling",
    intendedUse: "Create repeatable slab thickness for handbuilding prep.",
    aliases: ["5mm slab guide", "slab guide set", "slab roller guide"],
    approvedMaterial: "PLA",
    approvedSettings: {
      layerHeightMm: 0.24,
      nozzleMm: 0.4,
      infillPct: 30,
      supportStrategy: "none",
      buildPlate: "textured PEI",
    },
    estimatedGrams: 52,
    estimatedRuntimeMinutes: 160,
    evidenceChecklist: ["thickness gauge check", "flatness check"],
    replacementTrigger: null,
  },
  {
    id: "library.mold_registration_keys",
    name: "Mold registration key set",
    lane: "ceramics_tooling",
    intendedUse: "Provide repeatable alignment points for plaster mold setups.",
    aliases: ["mold key set", "mold registration keys", "mold register"],
    approvedMaterial: "PETG",
    approvedSettings: {
      layerHeightMm: 0.16,
      nozzleMm: 0.4,
      infillPct: 35,
      supportStrategy: "minimal",
      buildPlate: "textured PEI",
    },
    estimatedGrams: 140,
    estimatedRuntimeMinutes: 310,
    evidenceChecklist: ["fit check against mold", "repeat closure test"],
    replacementTrigger: "Reprint when a mold revision changes the alignment profile.",
  },
  {
    id: "library.label_clip_set",
    name: "Shelf label clip set",
    lane: "studio_infrastructure",
    intendedUse: "Hold shelf labels and QR tags on ware racks and drying shelves.",
    aliases: ["label clips", "shelf clip set", "qr label clip"],
    approvedMaterial: "PLA",
    approvedSettings: {
      layerHeightMm: 0.2,
      nozzleMm: 0.4,
      infillPct: 25,
      supportStrategy: "none",
      buildPlate: "textured PEI",
    },
    estimatedGrams: 36,
    estimatedRuntimeMinutes: 95,
    evidenceChecklist: ["clip retention test", "tag visibility photo"],
    replacementTrigger: "Reprint when a shelf lane changes or clips crack.",
  },
  {
    id: "library.cable_guide_pack",
    name: "Cable guide pack",
    lane: "studio_infrastructure",
    intendedUse: "Tidy sensor, light, and camera cables around the studio.",
    aliases: ["cable guides", "cable clips", "wire guide pack"],
    approvedMaterial: "PLA",
    approvedSettings: {
      layerHeightMm: 0.2,
      nozzleMm: 0.4,
      infillPct: 20,
      supportStrategy: "none",
      buildPlate: "textured PEI",
    },
    estimatedGrams: 28,
    estimatedRuntimeMinutes: 80,
    evidenceChecklist: ["adhesion test", "cable strain relief check"],
    replacementTrigger: null,
  },
  {
    id: "library.camera_mount_bracket",
    name: "Camera mount bracket",
    lane: "studio_infrastructure",
    intendedUse: "Mount a lightweight reference or process camera to a shelf edge.",
    aliases: ["camera bracket", "camera mount", "camera arm clamp"],
    approvedMaterial: "PETG",
    approvedSettings: {
      layerHeightMm: 0.16,
      nozzleMm: 0.4,
      infillPct: 40,
      supportStrategy: "minimal",
      buildPlate: "textured PEI",
    },
    estimatedGrams: 170,
    estimatedRuntimeMinutes: 345,
    evidenceChecklist: ["load test", "camera alignment photo", "shelf clearance check"],
    replacementTrigger: "Reprint when camera weight or shelf geometry changes.",
  },
];

export const fabricationConsumableStock: ConsumableStock[] = [
  {
    id: "stock.pla_black_primary",
    material: "PLA",
    label: "PLA Black - primary spool",
    remainingGrams: 920,
    dryingState: "dry_box",
    status: "ready",
    notes: ["Default spool for labels, clips, and general fixtures."],
  },
  {
    id: "stock.petg_natural_low",
    material: "PETG",
    label: "PETG Natural - low spool",
    remainingGrams: 180,
    dryingState: "recently_dried",
    status: "low",
    notes: ["Enough for small brackets, not enough for a long queue of structural parts."],
  },
];

export const fabricationMaintenanceBaseline: MaintenanceTask[] = [
  {
    id: "maint.build_plate_cleaning.open",
    taskType: "build_plate_cleaning",
    title: "Clean build plate before next tooling batch",
    description: "Wipe the textured plate and confirm first-layer readiness for the next run set.",
    conditionSignals: ["first_layer_failure", "bed_adhesion_noise"],
    status: "open",
    dueAfterHours: 12,
    dueAt: null,
    createdAt: "2026-03-14T00:00:00.000Z",
    lastCompletedAt: null,
  },
];

export const fabricationDryRunFixtures: FabricationDryRunFixture[] = [
  {
    label: "Known library reuse: glaze rack",
    request: {
      id: "dryrun.glaze_rack",
      title: "Glaze test tile rack",
      requester: "ops-primary",
      purpose: "Need another rack for the next glaze batch.",
      laneHint: "ceramics_tooling",
      urgency: "repeatable_tooling",
      linkedSource: null,
      desiredMaterial: null,
      estimatedGrams: null,
      estimatedRuntimeMinutes: null,
      dimensionsKnown: false,
      repeatableIntent: true,
      notes: "Reuse existing approved settings if possible.",
    },
    expectedRoute: "library_reuse",
    expectedOutcome: "planned",
  },
  {
    label: "Custom infrastructure helper: camera clamp",
    request: {
      id: "dryrun.camera_clamp",
      title: "Overhead camera arm clamp",
      requester: "ops-primary",
      purpose: "Need a new clamp to position a lightweight camera over the glaze table.",
      laneHint: "studio_infrastructure",
      urgency: "maintenance",
      linkedSource: "sketch://camera-arm-v2",
      desiredMaterial: "PETG",
      estimatedGrams: 120,
      estimatedRuntimeMinutes: 240,
      dimensionsKnown: true,
      repeatableIntent: true,
      notes: "Shelf thickness is already measured in the sketch.",
    },
    expectedRoute: "custom_job",
    expectedOutcome: "planned",
  },
  {
    label: "Stock alert: large PETG mold keys",
    request: {
      id: "dryrun.large_mold_keys",
      title: "Large mold registration key set",
      requester: "ops-primary",
      purpose: "Need a larger version of the mold registration keys for the next plaster test.",
      laneHint: "ceramics_tooling",
      urgency: "ops_critical",
      linkedSource: "cad://mold-key-set-v3",
      desiredMaterial: "PETG",
      estimatedGrams: 420,
      estimatedRuntimeMinutes: 520,
      dimensionsKnown: true,
      repeatableIntent: true,
      notes: "Do not start unless there is enough PETG to finish the full set.",
    },
    expectedRoute: "custom_job",
    expectedOutcome: "stock_alert",
  },
  {
    label: "Ambiguous request escalates",
    request: {
      id: "dryrun.ambiguous_fix",
      title: "Fix the shelf thing",
      requester: "ops-primary",
      purpose: "Something on the glaze shelf needs a printed fix.",
      laneHint: "studio_infrastructure",
      urgency: "maintenance",
      linkedSource: null,
      desiredMaterial: null,
      estimatedGrams: null,
      estimatedRuntimeMinutes: null,
      dimensionsKnown: false,
      repeatableIntent: false,
      notes: "No photo or measurements attached.",
    },
    expectedRoute: "escalate",
    expectedOutcome: "escalated",
  },
  {
    label: "Known library reuse: slab guide",
    request: {
      id: "dryrun.slab_guide",
      title: "5mm slab guide",
      requester: "ops-primary",
      purpose: "Need another 5mm guide pair for the handbuilding table.",
      laneHint: "ceramics_tooling",
      urgency: "repeatable_tooling",
      linkedSource: null,
      desiredMaterial: null,
      estimatedGrams: null,
      estimatedRuntimeMinutes: null,
      dimensionsKnown: false,
      repeatableIntent: true,
      notes: "Should be a straight library reuse.",
    },
    expectedRoute: "library_reuse",
    expectedOutcome: "planned",
  },
];
